services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-dev
    ports:
      - "27017:27017" # Maps the container port to the host machine
    environment:
      # Hardcoded credentials for local development
      - MONGO_INITDB_ROOT_USERNAME=wyd_admin
      - MONGO_INITDB_ROOT_PASSWORD=Test_Password
      - MONGODB_APP_USER=wyd_app_user
      - MONGODB_APP_PASSWORD=Test_User_Password
    volumes:
      # Use a named volume to persist data across container restarts
      - mongodb_data:/data/db
      # Mount the initialization script
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

volumes:
  mongodb_data: