services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: wyd_admin
      MONGO_INITDB_ROOT_PASSWORD: Golden_Song_Nose8
      MONGO_INITDB_DATABASE: wyd
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    restart: always

  rest_server:
    build:
      context: ./src
      dockerfile: Dockerfile
    container_name: rest_server
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - MONGODB_CONNECTION_STRING=mongodb://wyd_app_user:Use_Current_Universe1_Buffalo@mongodb_container:27017/wyd?authSource=wyd
      - MONGODB_DATABASE_NAME=wyd
    volumes:
      - ./src:/app
      - ~/.nuget/packages:/root/.nuget/packages
    depends_on:
      - mongodb
    restart: always
    command: dotnet watch run --urls "http://+:80" --non-interactive

volumes:
  mongodb_data:
    driver: local